from typing import Any, Awaitable, Protocol
from uuid import uuid4

from deepagents import create_deep_agent
from deepagents.middleware.subagents import CompiledSubAgent, SubAgent
from langchain.agents.middleware import AgentMiddleware
from langchain_aws.chat_models import ChatBedrock
from langchain_core.messages import (
    BaseMessage,
    SystemMessage,
)
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.tools import BaseTool, tool
from pydantic import BaseModel

from deepbrowser.agent.middleware import BROWSER_MSG_TAG, BrowserMiddleware, handle_tool_errors
from deepbrowser.agent.prompts import BROWSER_AGENT_SYSTEM_PROMPT
from deepbrowser.browser.cdp.browser import AsyncCDPBrowser
from deepbrowser.utils.langchain import structured_output_runnable_with_retries


@tool
def think_aloud(thought: str) -> None:
    """Think aloud"""
    pass


_OUTPUT_SYSTEM_PROMPT = """
## Role
You are a browser interaction agent. Your job is to take actions and data generated by
previous steps and generate a final output object that conforms to the provided schema
"""

# OutputModel = TypeVar(name="OutputModel", bound=BaseModel)


def _generate_structured_output(
    messages: list[BaseMessage], model: ChatBedrock, output_model: type[BaseModel]
) -> BaseModel:
    filtered_messages = [
        msg
        for msg in messages
        if not isinstance(msg, SystemMessage)
        and msg.additional_kwargs.get("TYPE") != BROWSER_MSG_TAG
    ]

    template = ChatPromptTemplate.from_messages(
        messages=[SystemMessage(content=_OUTPUT_SYSTEM_PROMPT), *filtered_messages]
    )

    invoke_args: dict[str, Any] = {}

    output = structured_output_runnable_with_retries(
        chat_template=template,
        model=model,
        output_model=output_model,
        invoke_args=invoke_args,
    )
    return output


class AgentInvoker(Protocol):
    def __call__(
        self,
        prompt: str,
        *,
        run_id: str | None = ...,
        config: dict[str, Any] | None = ...,
    ) -> Awaitable[dict[str, Any]]: ...


def browser_agent_builder(
    browser: AsyncCDPBrowser,
    model: ChatBedrock,
    *,
    additional_instructions: str = "",
    additional_tools: list[BaseTool] | None = None,
    additional_middleware: list[AgentMiddleware] | None = None,
    response_format: type[BaseModel] | None = None,
    subagents: list[SubAgent | CompiledSubAgent] | None = None,
    debug: bool = False,
) -> AgentInvoker:
    all_tools: list[BaseTool] = [
        *browser.browser_tools,
        *browser.page_tools,
        think_aloud,
    ]
    if additional_tools:
        all_tools.extend(additional_tools)

    all_middleware: list[AgentMiddleware[Any]] = [
        BrowserMiddleware(browser=browser),
        handle_tool_errors,
    ]
    if additional_middleware:
        all_middleware.extend(additional_middleware)

    agent = create_deep_agent(
        tools=all_tools,
        model=model,
        middleware=all_middleware,
        subagents=subagents,
        system_prompt=BROWSER_AGENT_SYSTEM_PROMPT
        + "\n"
        + (additional_instructions if additional_instructions else ""),
        debug=debug,
        # This doesn't seems to work
        # response_format=response_format
    )

    async def invoke(
        prompt: str, *, run_id: str | None = None, config: dict[str, Any] | None = None
    ) -> dict[str, Any]:
        if not run_id:
            run_id = str(uuid4())

        state = {
            "messages": [{"role": "user", "content": prompt}],
            "run_id": run_id,
            "iteration": 0,
        }
        result: dict[str, Any] = await agent.ainvoke(state, config if config else {})

        if response_format:
            result["structured_output"] = _generate_structured_output(
                messages=result["messages"], model=model, output_model=response_format
            )

        return result

    return invoke
